# Generated by Django 5.2.4 on 2025-07-30 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitydirection',
            options={'verbose_name': 'Направление деятельности', 'verbose_name_plural': 'Направления деятельности'},
        ),
    ]
